"""initial migration

Revision ID: 27507bc06298
Revises: 
Create Date: 2025-06-04 14:01:30.566423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27507bc06298'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='h2demo'
    )
    op.create_index(op.f('ix_h2demo_users_id'), 'users', ['id'], unique=False, schema='h2demo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_h2demo_users_id'), table_name='users', schema='h2demo')
    op.drop_table('users', schema='h2demo')
    # ### end Alembic commands ###
