"""Crear tabla users

Revision ID: 596205148cf4
Revises: 
Create Date: 2025-03-10 21:43:34.939938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596205148cf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='costos_ventas'
    )
    op.create_index(op.f('ix_costos_ventas_users_id'), 'users', ['id'], unique=False, schema='costos_ventas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costos_ventas_users_id'), table_name='users', schema='costos_ventas')
    op.drop_table('users', schema='costos_ventas')
    # ### end Alembic commands ###
